// src/components/messages/Messages.tsx
import { JSX } from 'preact'
import { useAppContext } from '../../model/AppContext'
import { MessageItem } from './MessageItem'
import { NarrratorItem } from './NarratorItem'
import { TalkContentText } from '../../model/TalkModels'

export function Messages (): JSX.Element {
  const context = useAppContext()
  const shownCharacters = context.shownCharacters
  const isNarrator = (idx: number): boolean => {
    return shownCharacters.value[idx].isNarrator
  }

  const setRef = (ref: HTMLDivElement | null): void => {
    context.messagesRef.value = ref
  }

  return (
    <div class='overflow-auto flex-initial grow px-1 pt-1 flex flex-col gap-2'>
      {context.messages.value.length !== 0
        ? context.messages.value.map((item, idx) => {
          if (isNarrator(item.characterIdx)) return <NarrratorItem idx={idx} item={item.message as TalkContentText} />
          return <MessageItem key={idx} message={item} idx={idx} />
        })
        : <Placeholder />}
      <div ref={setRef} />
    </div>
  )
}

function Placeholder (): JSX.Element {
  return (
    <div class='pointer-events-none w-full h-full flex items-center justify-center'>
      <span class='font-bold text-2xl text-gray-500'>Write something!</span>
    </div>
  )
}

// src/components/message/messages.svelte
<script lang="ts">
  import { messages } from '../../store/messages'
  import NarratorItem from './narrator-item.svelte'
  import TalkItem from './talk-item.svelte'

  export let session: number

  $: items = $messages[session]?.items ?? []
</script>

<div class="flex flex-col gap-1 grow overflow-scroll py-1 scrollbar-none">
  <!-- eslint-disable-next-line @typescript-eslint/strict-boolean-expressions -->
  {#each items as item (item.timestamp)}
    {#if item.narrator && item.content.type === 'text'}
      <NarratorItem content={item.content.content} />
    {:else}
      <TalkItem
        id={item.charId}
        content={item.content} />
    {/if}
  {:else}
    <div class="w-full h-full grow flex items-center justify-center">
      <p class="font-bold text-gray-600 text-xl">Write Something!</p>
    </div>
  {/each}
</div>

<style>
  .scrollbar-none {
    scrollbar-width: none;
  }
  .scrollbar-none::-webkit-scrollbar {
    display: none;
  }
</style>
